# .streamlit/secrets.toml
SUPABASE_URL = "https://jjgwhyuwugwqtzyfegoa.supabase.co"
SUPABASE_KEY = "sb_publishable_4B9mq1t692DUoXNHvuCr1g_n-nmNJRW"
SUPERADMIN_EMAIL = "alexmachado1607@gmail.com"
SUPERADMIN_PASSWORD = "Luisa@276148"